acme_blog:
    type: rest
    prefix: /api
    resource: "@AcmeBlogBundle/Resources/config/routes.yml"
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: /api/doc